FROM eclipse-temurin
RUN mkdir /opt/app
COPY target/sv2021-jvjbf-kepesitovizsga-potpot-0.0.1-SNAPSHOT.jar /opt/app/sv2021-jvjbf-kepesitovizsga-potpot.jar
CMD ["java", "-jar", "/opt/app/sv2021-jvjbf-kepesitovizsga-potpot.jar"]