### Rekorder mentése

POST http://localhost:8080/api/recorders
Content-Type: application/json

{
  "name": "Ken",
  "dateOfBirth": "1999-08-20"
}

### Rekorder mentése - hibakezelés

POST http://localhost:8080/api/recorders
Content-Type: application/json

{
  "name": "",
  "dateOfBirth": "1999-09-09"
}

### Bizonyos rekorderek listázása

GET http://localhost:8080/api/recorders